rsdl-js: doc comments
oasis-open/odata-rapid pull request #259
Opened 2021-07-09 19:22 UTC by ralfhandl

PoC for #247 247

2021-07-22 16:52 UTC, ralfhandl commented on tools/rsdl/rsdl-js/test/parser.test.js
> +             ## has nice properties
Also test empty lines between doc comments

2021-07-22 16:54 UTC, ralfhandl commented on tools/rsdl/rsdl-js/test/parser.test.js
> +             ## has nice properties
And plain comments interspersed within a block of doc comments

2021-07-22 17:01 UTC, mikepizzo commented on tools/rsdl/rsdl-js/lib/parser.js
> +      const name = `${this.annotatable[0].prefix}@Org.OData.Core.V1.Documentation`;
Should be Org.OData.Core.V1.Description

2021-07-22 17:03 UTC, mikepizzo requested changes
I like it, but annotation should be Org.OData.Core.V1.Description rather than Org.OData.Core.V1.Documentation

2021-07-22 17:17 UTC, ralfhandl commented on tools/rsdl/rsdl-js/test/parser.test.js
> +             ## has nice properties
Done

2021-07-30 14:09 UTC, ralfhandl commented
> I like it, but annotation should be Org.OData.Core.V1.Description rather than Org.OData.Core.V1.Documentation

Done

2021-08-19 15:28 UTC, mikepizzo approved these changes

2021-08-19 15:28 UTC, chrisspre approved these changes

2021-08-19 15:28 UTC, merged