RSDL containment
oasis-open/odata-rapid pull request #261
Opened 2021-07-13 15:56 UTC by ralfhandl

Part of #242

2021-08-19 15:21 UTC, chrisspre approved these changes

2021-08-19 15:23 UTC, chrisspre approved these changes

2021-09-09 15:08 UTC, mikepizzo requested changes
This solves for containment, but doesn't provide a means of specifying a navigation property binding.  We will probably want to align what we do for containment with specifying a nav property binding, since the two are inversely related.

2021-09-16 18:03 UTC, mikepizzo commented
As per 2021-9-16 meeting, current thinking is to use our path-based section to specify nav prop bindings through a new "targets" keyword. Absence of specifying a target for a path implies containment, so we would not need to add the "*" syntax.

2021-09-17 07:26 UTC, closed without merging